presentation/Store.Web/Models/ErrorViewModel.cs
using System;

namespace Store.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

presentation/Store.Web/Models/OrderModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Store.Web.Models
{
    public class OrderModel
    {
        public int Id { get; set; }

        public OrderItemModel[] Items { get; set; } = new OrderItemModel[0];

        public int TotalCount { get; set; }

        public decimal TotalPrice { get; set; }
    }
}

presentation/Store.Web/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using Store.Web.App;

namespace Store.Web.Controllers
{
    public class BookController : Controller
    {
        private readonly BookService bookService;

        public BookController(BookService bookService)
        {
            this.bookService = bookService;
        }

        public IActionResult Index(int id)
        {
            var model = bookService.GetById(id);

            return View(model);
        }
    }
}

presentation/Store.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Store.Web.Models;
using System.Diagnostics;

namespace Store.Web.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

presentation/Store.Web/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Collections.Generic;
using Store.Contractors;
using Store.Web.Contractors;
using Store.Web.App;
using System;

namespace Store.Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly OrderService orderService;
        private readonly IEnumerable<IDeliveryService> deliveryServices;
        private readonly IEnumerable<IPaymentService> paymentServices;
        private readonly IEnumerable<IWebContractorService> webContractorServices;

        public OrderController(OrderService orderService,
                               IEnumerable<IDeliveryService> deliveryServices,
                               IEnumerable<IPaymentService> paymentServices,
                               IEnumerable<IWebContractorService> webContractorServices) // Constructor Injection
        {
            this.orderService = orderService;
            this.deliveryServices = deliveryServices;
            this.paymentServices = paymentServices;
            this.webContractorServices = webContractorServices;
        }

        [HttpGet]
        public IActionResult Index()
        {
            if (orderService.TryGetModel(out OrderModel model))
                return View(model);

            return View("Empty");
        }

        [HttpPost]
        public IActionResult AddItem(int bookId, int count = 1)
        {
            orderService.AddBook(bookId, count);

            return RedirectToAction("Index", "Book", new { id = bookId });
        }

        [HttpPost]
        public IActionResult UpdateItem(int bookId, int count)
        {
            var model = orderService.UpdateBook(bookId, count);

            return View("Index",model);
        }

        [HttpPost]
        public IActionResult RemoveItem(int bookId)
        {
            var model = orderService.RemoveBook(bookId);

            return View("Index", model);
        }

        [HttpPost]
        public IActionResult SendConfirmation(string cellPhone)
        {
            var model = orderService.SendConfirmation(cellPhone);

            return View("Confirmation", model);
        }

        [HttpPost]
        public IActionResult ConfirmCellPhone(string cellPhone, int confirmationCode)
        {
            var model = orderService.ConfirmCellPhone(cellPhone, confirmationCode);

            if (model.Errors.Count > 0)
                return View("Confirmation", model);

            var deliveryMethods = deliveryServices.ToDictionary(service => service.Name,
                                                                service => service.Title);

            return View("DeliveryMethod", deliveryMethods);
        }


        [HttpPost]
        public IActionResult StartDelivery(string serviceName)
        {
            var deliveryService = deliveryServices.Single(service => service.Name == serviceName);
            var order = orderService.GetOrder();
            var form = deliveryService.FirstForm(order);

            var webContractorService = webContractorServices.SingleOrDefault(service => service.Name == serviceName);
            if (webContractorService == null)
                return View("DeliveryStep", form);

            var returnUri = GetReturnUri(nameof(NextDelivery));
            var redirectUri = webContractorService.StartSession(form.Parameters, returnUri);

            return Redirect(redirectUri.ToString());
        }

        private Uri GetReturnUri(string action)
        {
            var builder = new UriBuilder(Request.Scheme, Request.Host.Host)
            {
                Path = Url.Action(action),
                Query = null,
            };

            if (Request.Host.Port != null)
                builder.Port = Request.Host.Port.Value;

            return builder.Uri;
        }

        [HttpPost]
        public IActionResult NextDelivery(string serviceName, int step, Dictionary<string, string> values)
        {
            var deliveryService = deliveryServices.Single(service => service.Name == serviceName);

            var form = deliveryService.NextForm(step, values);
            if (!form.IsFinal)
                return View("DeliveryStep", form);

            var delivery = deliveryService.GetDelivery(form);
            orderService.SetDelivery(delivery);

            var paymentMethods = paymentServices.ToDictionary(service => service.Name,
                                                              service => service.Title);

            return View("PaymentMethod", paymentMethods);
        }

        [HttpPost]
        public IActionResult StartPayment(string serviceName)
        {
            var paymentService = paymentServices.Single(service => service.Name == serviceName);
            var order = orderService.GetOrder();
            var form = paymentService.FirstForm(order);

            var webContractorService = webContractorServices.SingleOrDefault(service => service.Name == serviceName);
            if (webContractorService == null)
                return View("PaymentStep", form);

            var returnUri = GetReturnUri(nameof(NextPayment));
            var redirectUri = webContractorService.StartSession(form.Parameters, returnUri);

            return Redirect(redirectUri.ToString());
        }

        [HttpPost]
        public IActionResult NextPayment(string serviceName, int step, Dictionary<string, string> values)
        {
            var paymentService = paymentServices.Single(service => service.Name == serviceName);

            var form = paymentService.NextForm(step, values);
            if (!form.IsFinal)
                return View("PaymentStep", form);

            var payment = paymentService.GetPayment(form);
            var model = orderService.SetPayment(payment);

            return View("Finish", model);
        }
    }
}

presentation/Store.Web/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using Store.Web.App;

namespace Store.Web.Controllers
{
    public class SearchController : Controller
    {
        private readonly BookService bookService;

        public SearchController(BookService bookService)
        {
            this.bookService = bookService;
        }

        // /search/index?query=title
        // IActionResult - результат какого-то действия. Это либо какая-то готовая страница(View), набор заголовков в протоколе HTTP или же статус ошибки и тп.
        public IActionResult Index(string query)
        {
            var books = bookService.GetAllByQuery(query);

            return View("Index",books); // Указываем имя шаблона в папке View, который будет вызываться, и передаём массив книг, то есть модель
        }
    }
}

presentation/Store.Web/Views/Book/Index.cshtml
@model BookModel

@{
    ViewData["Title"] = Model.Title; // Заголовок страницы
}

<h1>@Model.Title</h1>
<p><strong>@Model.Author</strong></p>
<p>@Model.Description</p>
<p>Цена <strong>@Model.Price</strong></p>
<form action="@Url.Action(nameof(OrderController.AddItem), "Order")" method="post">
    <input type="hidden" name="bookId" value="@Model.Id" />
    <button class="btn btn-success" type="submit">В корзину</button>
</form>

presentation/Store.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Интернет-магазин";
}

<h3>Тема работы: "Книжный интернет-магазин"</h3>
<p>
    На сегодняшний день, огромную популярность среди веб-сервисов приобрели интернет-магазины (и все схожие с ними продукты). Каждый человек сталкивается с подобными ресурсами в своей жизни. Кто-то просто пользуется, а кто-то пытается понять и разобраться, как всё устроено, к чему приводит то или иное дейтсвие на странице.
    В рамках своей работы, я попытался реализовать сам механизм, который максимально схож с нынешними гигантами, как Amazon, eBay, Ozon и др.
</p>
<p>
    Промышленная разработка — лучшая ситуация для самообучения. В рамках напиания работы можно получить не только предметные знания в области web-разработки, но и попрактиковаться с изученными на текущий период времени технологиями.
</p>

<h3>Проект</h3>
<p>
    В качестве своего проекта я выбрал книжный интернет-магазин. Каждый из нас покупал книги в интернете и хорошо представляет предметную область. Нам не придётся пару недель разбираться в том, что мы хотим сделать.
</p>
<p>
    С другой стороны, интернет-магазин уже достаточно велик и практичен, чтобы мы могли столкнуться с проблемами и понять, как абстрактные знания помогают их решать.
</p>

<h2>О проекте</h2>
<p>
    Продолжительность работы велась пару месяцев. Я попытался учесть все аспекты и сделать полноценный продукт.
</p>

<h3>Темы, изученные в рамках проектирования</h3>
<ul>
    <li>SQL</li>
    <li>git и GitHub</li>
    <li>Agile: бэклог, пользовательские истории, итерации</li>
    <li>Модульное тестирование</li>
    <li>Паттерны проектирования</li>
    <li>Принципы SOLID</li>
    <li>DDD (Domain Driven Design)</li>
    <li>MVC</li>
    <li>Entity Framework</li>
</ul>
<p>
    p.s. Таже, помимо языков программирования, указанных в документации, использовались HTML, CSS и JavaScript.
</p>

<p>
    <a href="https://www.linkedin.com/in/glebyshka/">Мой LinkedIn</a>.
</p>

presentation/Store.Web/Views/Order/Confirmation.cshtml
@model OrderModel

@{
    ViewData["Title"] = "Подтверждение мобильного";
}

<h1>Подтверждение мобильного</h1>

<p>
    Введите <em>код подтверждения</em> из SMS.
</p>

<form action="@Url.Action(nameof(OrderController.ConfirmCellPhone))" method="post">
    <input type="hidden" name="cellPhone" value="@Model.CellPhone" />
    <div class="form-group">
        <label for="confirmationCode">Код подтверждения</label>
        <input type="text" class="form-control" name="confirmationCode" placeholder="0000"/>
        @if (Model.Errors.ContainsKey("confirmationCode"))
        {
            <small class="form-text text-danger">@Model.Errors["confirmationCode"]</small> 
        }
    </div>
    <button type="submit" class="btn btn-success">Проверить</button>
</form>

<p>
    Если на ваш номер SMS не пришла в течение минуты, проверьте правильность номера и
    повторите отправку кода.
</p>

<form action="@Url.Action("SendConfirmationCode")" method="post">
    <div class="form-group">
        <label for="cellPhone">Мобильный телефон</label>
        <input type="text" class="form-control" name="cellPhone" value="@Model.CellPhone" />
        @if (Model.Errors.ContainsKey("cellPhone"))
        {
            <small class="form-text text-danger">@Model.Errors["cellPhone"]</small>
        }
    </div>
    <button type="submit" class="btn btn-success">Повторить код</button>
</form>

presentation/Store.Web/Views/Order/DeliveryMethod.cshtml
@model IReadOnlyDictionary<string,string>
@{
    ViewData["Title"] = "Способ доставки";
}

<h1>Способ доставки</h1>

<form action="@Url.Action(nameof(OrderController.StartDelivery))" method="post">
    <div class="form-group">
        <label for="code">Способ доставки:</label>
        <select class="form-control" name="serviceName">
            @foreach (var method in Model)
	         {
		        <option value="@method.Key">@method.Value</option>
	         }
        </select>
    </div>
    <button type="submit" class="btn btn-success">Далее</button>
</form>

presentation/Store.Web/Views/Order/DeliveryStep.cshtml
@using Store.Web.Controllers
@model Form

@{
    ViewData["Title"] = "Параметры доставки";
}

<h1>Параметры доставки</h1>
<form action="@Url.Action(nameof(OrderController.NextDelivery))" method="post">
    <input type="hidden" name="serviceName" value="@Model.ServiceName" />
    <input type="hidden" name="step" value="@Model.Step" />
    @foreach (var parameter in Model.Parameters)
    {
        <input type="hidden" name="values[@parameter.Key]" value="@parameter.Value" />
    }
    @foreach (var field in Model.Fields)
    {
        if (field is SelectionField selectionField)
        {
            <div class="form-group">
                <label for="values[@field.Name]">@field.Label</label>
                <select class="form-control" name="values[@field.Name]">
        
                    @foreach (var item in selectionField.Items)
                    {
                        <option value="@item.Key">@item.Value</option>
                    }
                </select>
            </div>
        }
    }
    <button type="submit" class="btn btn-success">Далее</button>
</form>

presentation/Store.Web/Views/Order/Empty.cshtml
@{
    ViewData["Title"] = "Empty";
}

<h1>Корзина пуста</h1>

presentation/Store.Web/Views/Order/Finish.cshtml
@model OrderModel
@{
    ViewData["Title"] = "Заказ оформлен";
}

<p>
    Заказ оформлен. Мы собираем его, чтобы передатьв службу доставки.
    Ждите SMS.
</p>

<table class="table table-sm table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">№</th>
            <th scope="col">Автор</th>
            <th scope="col">Название</th>
            <th scope="col">Количество</th>
            <th scope="col">Цена</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Items.Length; i++)
        {
            <tr>
                <td class="text-right">@(i + 1)</td>
                <td>@Model.Items[i].Author</td>
                <td>@Model.Items[i].Title</td>
                <td class="text-right">@Model.Items[i].Count</td>
                <td class="text-right">@Model.Items[i].Price</td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Итого</td>
            <td class="text-right">@Model.TotalCount</td>
            <td class="text-right">@Model.TotalPrice</td>
        </tr>
    </tfoot>
</table>

<strong>Доставка</strong>
<pre>
@Model.DeliveryDescription
</pre>

<strong>Оплата</strong>
<pre>
@Model.PaymentDescription
</pre>

<p>
    <a href="@Url.Action("Index","Home")">Вернуться в магазин.</a>
</p>

presentation/Store.Web/Views/Order/Index.cshtml
@model OrderModel

@{
    ViewData["Title"] = "Корзина";
}

<h1>Корзина</h1>

<table class="table table-sm table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">№</th>
            <th scope="col">Автор</th>
            <th scope="col">Название</th>
            <th scope="col">Количество</th>
            <th scope="col">Цена</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Items.Length; i++)
        {
            <tr>
                <td class="text-right">@(i+1)</td>
                <td>@Model.Items[i].Author</td>
                <td>@Model.Items[i].Title</td>
                <td class="text-right">@Model.Items[i].Count</td>
                <td class="text-right">@Model.Items[i].Price</td>
                <td class="text-center">
                    <form class="form-inline" action="@Url.Action("RemoveItem","Order")" method="post">
                        <input type="hidden" name="bookId" value="@Model.Items[i].BookId" />
                        <button class="btn btn-danger" type="submit">Удалить</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Итого</td>
            <td class="text-right">@Model.TotalCount</td>
            <td class="text-right">@Model.TotalPrice</td>
        </tr>
    </tfoot>
</table>

<p>
    Для оформления заказа необходимо подтвердить номер вашего мобильного.
    Введите номер и нажмите <em>Отправить код</em>. На ваш номер будет отправлен *код подтверждения*.
</p>

<form action="@Url.Action(nameof(OrderController.SendConfirmation))" method="post">
    <div class="form-group">
        <label for="cellPhone">Мобильный телефон</label>
        <input type="text" class="form-control" name="cellPhone" placeholder="+79876543210" value="+79876543210" />
        @if (Model.Errors.ContainsKey("cellPhone"))
        {
            <small class="form-text text-danger">@Model.Errors["cellPhone"]</small>
        }
    </div>
    <button type="submit" class="btn btn-success">Отправить код</button>
</form> 

presentation/Store.Web/Views/Order/PaymentMethod.cshtml
@model IReadOnlyDictionary<string,string>
@{
    ViewData["Title"] = "Способ оплаты";
}

<h1>Способ оплаты</h1>

<form action="@Url.Action(nameof(OrderController.StartPayment))" method="post">
    <div class="form-group">
        <label for="code">Способ оплаты:</label>
        <select class="form-control" name="serviceName">
            @foreach (var method in Model)
	         {
		        <option value="@method.Key">@method.Value</option>
	         }
        </select>
    </div>
    <button type="submit" class="btn btn-success">Далее</button>
</form>

presentation/Store.Web/Views/Order/PaymentStep.cshtml
@using Store.Web.Controllers
@model Form

@{
    ViewData["Title"] = "Параметры оплаты";
}

<h1>Параметры оплаты</h1>
<form action="@Url.Action(nameof(OrderController.NextPayment))" method="post">
    <input type="hidden" name="serviceName" value="@Model.ServiceName" />
    <input type="hidden" name="step" value="@Model.Step" />
    @foreach (var parameter in Model.Parameters)
    {
        <input type="hidden" name="values[@parameter.Key]" value="@parameter.Value" />
    }
    @foreach (var field in Model.Fields)
    {
        if (field is SelectionField selectionField)
        {
            <div class="form-group">
                <label for="values[@field.Name]">@field.Label</label>
                <select class="form-control" name="values[@field.Name]">

                    @foreach (var item in selectionField.Items)
                    {
                        <option value="@item.Key">@item.Value</option>
                    }
                </select>
            </div>
        }
    }
    <button type="submit" class="btn btn-success">Далее</button>
</form>

presentation/Store.Web/Views/Search/Index.cshtml
@model IReadOnlyCollection<BookModel>

@{
    ViewData["Title"] = "Результаты поиска";
}

<h1>Результаты поиска</h1>

@if (Model.Count == 0)
{
    <p>Ничего не найдено.</p>
}
else
{
    <ul>
        @foreach(var book in Model)
         {
             <li><a href="@Url.Action("Index","Book", new { id = book.Id })">@book.Title</a></li>
         }
    </ul>
}

presentation/Store.Web/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "Страница не найдена";
}

<h1 class="text-danger">Страница не найдена</h1>

presentation/Store.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Интернет-магазин</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Интернет-магазин</a>
            <form class="form-inline my-2 my-lg-0" action="@Url.Action("Index","Search")" method="get">
                <input class="form-control mr-sm-2" type ="search" name="query" placeholder="автор или название" />
                <button class="btn btn-outline-success my-2 my-sm-0" type ="submit">Искать</button>
            </form>
            <span class="navbar-text ml-auto">
                @{ 
                    if (Context.Session.TryGetCart(out Cart cart) && cart.TotalCount > 0)
                    {
                        <a href ="@Url.Action("Index","Order")">Товаров @cart.TotalCount на сумму @cart.TotalPrice</a>
                    }
                    else
                    {
                        @:Корзина пуста
                    }
                }
            </span> 
        </nav>
    </header>

    <div class="container">
        <main>
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>